#!/usr/bin/env python3
import subprocess
MESSAGE_FLAG = "BOT MESSAGE: AUTO BUMP VERSION"


def shell_call(cmd:str):
    s = subprocess.run(cmd, shell=True, capture_output=True).stdout
    return s.decode("utf-8").strip()


def bump_version():
    def extract_ver(s)->str:
        with_quotes = s.split("=")[1].strip()
        wo_q = with_quotes.replace('"', '')
        return wo_q


    shell_call("cargo bump patch")
    diff = shell_call("git diff Cargo.toml| grep version | egrep ^[+-]").split("\n")
    assert(len(diff) == 2)
    vers = [extract_ver(v) for v in diff]
    return (vers[0], vers[1])


def main():
    branch_name = shell_call("git branch --show-current")
    if branch_name not in ['master'] and branch_name != 'bump':
        print("Current branch  ({})  is not for release. Exiting".format(branch_name))
    commit_log = shell_call("git log --name-status -1")
    if MESSAGE_FLAG in commit_log:
        print("Last commit is generated by bot. Exiting")
    (old_ver, new_ver) = bump_version()
    new_commit_message = MESSAGE_FLAG + " From {} To {}".format(old_ver, new_ver)
    git_commit_cmd = "git commit -a -m '{}'".format(new_commit_message)
    shell_call(git_commit_cmd)


main()